### PR TITLE
#28 Fix bug where you can click back button on home page

### LINKED ISSUE #28: Stop back button from navigating you outside the application
When you click the back button on the home page, you get redirected to the last page you were on (i.e Google)

### PR DESCRIPTION
**Pull request by Ray-F**
Closes #28

### CODE REVIEW

**Review by Mykhol — COMMENTED** [review]
Do you think maybe it makes sense to remove the Home Button and Back Button from the home page, as it literally serves no purpose?

**Comment by Ray-F** [comment]
> Do you think maybe it makes sense to remove the Home Button and Back Button from the home page, as it literally serves no purpose?

Yep you're completely right, I tried a few things to see if we can remove it on the home page, but it's actually quite a bit harder to actually do since these back buttons are hosted in the MainRouter class, and there isn't an easy way to detect changes when switching pages. I wanted to merge these into master first to fix the issue first, and then perhaps have a think about what is a better solution

**Comment by Mykhol** [comment]
> > Do you think maybe it makes sense to remove the Home Button and Back Button from the home page, as it literally serves no purpose?
> 
> Yep you're completely right, I tried a few things to see if we can remove it on the home page, but it's actually quite a bit harder to actually do since these back buttons are hosted in the MainRouter class, and there isn't an easy way to detect changes when switching pages. I wanted to merge these into master first to fix the issue first, and then perhaps have a think about what is a better solution

Great happy to do that. Will have a chat to you about this later. Will create an issue for this too.

**Review by Mykhol — APPROVED** [review]
Good work, efectively remedies the issue.

**Pull request merged**
